In [1]:
import torch

In [2]:
# The autograd package provides automatic differentiation 
# for all operations on Tensors

# requires_grad = True -> tracks all operations on the tensor. 
x = torch.randn(3, requires_grad=True)
y = x + 2

In [3]:
# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user -> grad_fn is None
print(y)
print(y.grad_fn)

tensor([-0.8419,  0.8580, -0.3918], requires_grad=True)
tensor([1.1581, 2.8580, 1.6082], grad_fn=<AddBackward0>)


In [4]:
# Do more operations on y
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([ 4.0235, 24.5040,  7.7589], grad_fn=<MulBackward0>)
tensor(12.0955, grad_fn=<MeanBackward0>)


In [5]:
# Let's compute the gradients with backpropagation
# When we finish our computation we can call .backward() and have all the gradients computed automatically.
# The gradient for this tensor will be accumulated into .grad attribute.
# It is the partial derivate of the function w.r.t. the tensor

z.backward()
print(x.grad) # dz/dx

tensor([2.3162, 5.7159, 3.2164])


In [7]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms