In [2]:
import torch
from sklearn.datasets import make_classification

In [4]:
class CustomDataset:
    def __init__(self,data,targets):
        self.data=data
        self.targets=targets
    def __len__(self):
        return self.data.shape[0]
    def __getItem(self,idx):
        current_sample=self.data[idx:]
        current_target=self.targets[idx]
        return {
            "sample" : torch.tensor(current_sample,dtype=float),
            "target" : torch.tensor(current_target,dtype=long)
        }


In [5]:
data,targets = make_classification(n_samples=1000)

In [6]:
custom_dataset=CustomDataset(data,targets)

In [7]:
len(custom_dataset)

1000

In [9]:
custom_dataset

In [16]:
custom_dataset.data

array([[-1.56572167, -0.22364612, -0.67773925, ..., -0.80477605,
        -1.64401284, -0.01360612],
       [-0.66344244,  1.51077831, -1.22883461, ..., -0.69993522,
         0.65642928, -0.74982958],
       [ 0.9094351 ,  0.77233911,  0.80503583, ..., -0.83241086,
        -0.86982056,  1.07591575],
       ...,
       [ 0.52331217, -0.42885179,  0.89203693, ...,  0.08047257,
        -1.26222097,  1.39517541],
       [ 1.98707231,  0.73087926,  0.50542479, ...,  3.12668219,
        -1.80861503,  1.32975548],
       [ 1.41886832,  0.13058171,  0.22676659, ..., -0.91507713,
        -0.28702559,  0.82211129]])

In [17]:
custom_dataset.targets

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [19]:
custom_dataset.data[0]

array([-1.56572167, -0.22364612, -0.67773925, -0.5072904 ,  0.1791473 ,
        1.04057639, -0.46572002,  0.15898416,  1.20447766, -0.57689251,
       -0.49347789,  2.0773894 ,  1.593706  ,  1.4276175 ,  0.70706738,
        0.5218009 ,  1.32261296, -0.80477605, -1.64401284, -0.01360612])

In [20]:
custom_dataset.targets[1]

0

In [22]:
custom_dataset['sample']

TypeError: 'CustomDataset' object is not subscriptable