In [1]:
import torch

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)


tensor([-4.8055e-05])
tensor([2.2698e-32, 3.0613e-41, 2.3127e-32])
tensor([[-6.2575e-05,  4.5890e-41, -6.2575e-05],
        [ 4.5890e-41,  4.4842e-44,  0.0000e+00]])
tensor([[[ 2.1452e-32,  3.0613e-41,  2.1194e-32],
         [ 3.0613e-41,  1.1210e-43,  0.0000e+00]],

        [[ 8.9683e-44,  0.0000e+00,  2.7189e+19],
         [ 3.0609e-41, -6.2575e-05,  4.5890e-41]]])


In [5]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)


tensor([[0.6718, 0.8471, 0.3573],
        [0.3589, 0.0644, 0.2739],
        [0.8612, 0.7038, 0.6550],
        [0.9709, 0.9143, 0.5588],
        [0.3522, 0.5485, 0.6450]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# check size
print(x.size())

# check data type
print(x.dtype)

torch.Size([5, 3])
torch.float32


In [7]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [8]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())


torch.Size([2])


In [9]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)


In [10]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)


In [11]:
z

tensor([[1.1807, 1.3094],
        [0.9766, 1.6562]])

In [12]:
# substraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)


In [13]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.7873, 0.7920, 0.8814],
        [0.3952, 0.6525, 0.8965],
        [0.8524, 0.3274, 0.7501],
        [0.7795, 0.7955, 0.4617],
        [0.6621, 0.7107, 0.1175]])
tensor([0.7873, 0.3952, 0.8524, 0.7795, 0.6621])
tensor([0.3952, 0.6525, 0.8965])
tensor(0.6525)


In [14]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())


0.6525477766990662


In [15]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [17]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

In [20]:
z

tensor([[-1.8474, -1.1460,  1.3858, -0.5763,  0.6070, -1.1256,  0.0645, -1.5780],
        [-0.4388, -1.5656, -0.2688, -0.5052,  0.5020, -1.6847,  0.5946, -0.7093]])